json_data = {
    "BillingPeriod":{
       "From":"990000000",
       "To":"995000000",
       "InvoiceAuthorization":"18760000001",
       "StartDate":"2019-01-19",
       "EndDate":"2030-01-19"
    },
    "Additional":{
       "CreateBy":"Mauricio",
       "UpdateBy":"John Henry",
       "CUFE":"",
       "Contingency":"N",
       "SendEmail":True,
       "DianSoftwareId":"b002d922-3fb3-499b-91f7-5bcb05eb5762",
       "DianPin":"12345",
       "DianTechnicalKey":"fc8eac422eba16e22ffd8c6f94b3f40a6e38162c",
       "DianTestSetId":"7de7c2b8-9397-4607-bb97-76122d9f2735",
       "ProfileExecutionId":"2"
    },
    "SeriePrefix":"SETP",
    "SerieNumber":"990000000",
    "IssueDate":"IssueDate",
    "DueDate":"2022-01-11",
    "IssueTime":"IssueTime",
    "CorrelationDocumentId":"paj/UzB12e-SETT-100471-20220111",
    "SerieExternalKey":"paj/UzB12e",
    "DeliveryDate":"2022-01-11",
    "DeliveryTime":"14:30:00-05:00",
    "PaymentMeans":[
       {
          "Code":"42",
          "Mean":"2",
          "DueDate":"2022-01-11"
       }
    ],
    "IssuerParty":{
       "LegalType":"1",
       "Identification":{
          "DocumentNumber":"830506365",
          "DocumentType":"NIT",
          "CountryCode":"CO",
          "CheckDigit":"7"
       },
       "Name":"SOFTPYMES SAS",
       "Email":"facturacion@softpymes.com.co",
       "Address":{
          "DepartmentCode":"76",
          "DepartmentName":"VALLE DEL CAUCA",
          "CityCode":"76001",
          "CityName":"CALI",
          "AddressLine":"CLL 21 24 55 NORTE",
          "PostalCode":"760131",
          "Country":"CO"
       },
       "TaxScheme":"IVA",
       "ResponsabilityTypes":[
          "O-23"
       ]
    },
    "CustomerParty":{
       "TeleFax":"6772171",
       "DocumentContacts":[
          {
             "Name":"PRINCIPAL",
             "Type":"DeliveryContact",
             "Telephone":"6772171"
          }
       ],
       "LegalType":"1",
       "Identification":{
          "DocumentNumber":"901262833",
          "DocumentType":"NIT",
          "CountryCode":"CO",
          "CheckDigit":"0"
       },
       "Name":"INMOBILIER SAS",
       "Email":"mgarcia@softpymes.com.co",
       "Address":{
          "DepartmentCode":"11",
          "DepartmentName":"CUNDINAMARCA",
          "CityCode":"11001",
          "CityName":"BOGOTA",
          "AddressLine":"CLL 161 15 44 NORTE",
          "PostalCode":"110131",
          "Country":"CO"
       },
       "TaxScheme":"IVA",
       "ResponsabilityTypes":[
          "O-23"
       ]
    },
    "Currency":"COP",
    "OperationType":"01",
    "Lines":[
       {
          "Number":"1",
          "Quantity":"1.00",
          "QuantityUnitOfMeasure":"NAR",
          "TaxSubTotals":[
             {
                "TaxableAmount":"300000.00",
                "TaxCategory":"IVA",
                "TaxPercentage":"19.00",
                "PerUnitAmount":"",
                "TaxAmount":"57000.00"
             }
          ],
          "TaxTotals":[
             {
                "TaxCategory":"IVA",
                "TaxAmount":"57000.00",
                "RoundingAmount":"2"
             }
          ],
          "UnitPrice":"300000.00",
          "GrossAmount":"300000.00",
          "NetAmount":"300000.00",
          "AllowanceCharges":[
             {
                "ChargeIndicator":"false",
                "BaseAmount":"300000",
                "ReasonCode":"string",
                "Reason":"descuento",
                "Amount":"0",
                "Percentage":"0",
                "SequenceIndicator":"string"
             }
          ],
          "Item":{
             "SellerItemIdentification":"ACT-FE",
             "Description":"ACTIVACION FACTURACIÓN ELECTRÓNICA",
             "IncomePurposeCode":"0",
             "UnitsPerPackage":"",
             "BrandName":"",
             "ModelName":""
          },
          "WithholdingTaxSubTotals":[
             {
                "WithholdingTaxCategory":"RETERENTA",
                "TaxPercentage":"4.00",
                "TaxableAmount":"300000.00",
                "TaxAmount":"12000.00"
             }
          ],
          "WithholdingTaxTotals":[
             {
                "WithholdingTaxCategory":"RETERENTA",
                "TaxAmount":"12000.00",
                "TaxableAmount":"300000.00"
             }
          ]
       }
    ],
    "TaxSubTotals":[
       {
          "TaxCategory":"IVA",
          "TaxPercentage":"19.00",
          "TaxableAmount":"300000.00",
          "TaxAmount":"57000.00"
       }
    ],
    "WithholdingTaxSubTotals":[
       {
          "WithholdingTaxCategory":"RETERENTA",
          "TaxPercentage":"4.000",
          "TaxableAmount":"300000.00",
          "TaxAmount":"12000.00"
       }
    ],
    "AllowanceCharges":[
       {
          "ChargeIndicator":"string",
          "BaseAmount":"string",
          "ReasonCode":"string",
          "Reason":"string",
          "Amount":"string",
          "Percentage":"string",
          "SequenceIndicator":"string"
       }
    ],
    "TaxTotals":[
       {
          "TaxCategory":"IVA",
          "TaxAmount":"57000.00",
          "RoundingAmount":"0"
       }
    ],
    "WithholdingTaxTotals":[
       {
          "WithholdingTaxCategory":"RETERENTA",
          "TaxAmount":"13200.00"
       }
    ],
    "Total":{
       "GrossAmount":"300000.00",
       "TotalBillableAmount":"357000.00",
       "PayableAmount":"357000.00",
       "TaxableAmount":"300000.00",
       "AllowancesTotalAmount":"0",
       "ChargesTotalAmount":"0",
       "PrePaidTotalAmount":"0",
       "TotalIva":"0.00",
       "TotalIca":"0.00",
       "TotalTaxConsume":"0.00"
    },
    "DocumentReferences":[
       {
          "DocumentReferred":"string",
          "IssueDate":"string",
          "Type":"string",
          "OtherReferenceTypeId":"string",
          "OtherReferenceTypeDescription":"string",
          "DocumentReferredCUFE":"string"
       }
    ],
    "AdditionalCustomers":[
       {
          "Name":"string",
          "CommercialRegistrationNumber":"string",
          "Identification":{
             "DocumentNumber":"string",
             "DocumentType":"string",
             "CountryCode":"string",
             "CheckDigit":"string"
          },
          "ParticipationPercentage":"string"
       }
    ],
    "PdfData":{
       "Pdf":"datapdf_encode"
    }
 }
